// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/poconnor/graft/internal/lock (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock/store.go -package=mock github.com/poconnor/graft/internal/lock Store
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	lock "github.com/poconnor/graft/internal/lock"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStore) Load(root string) (lock.Lock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", root)
	ret0, _ := ret[0].(lock.Lock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStoreMockRecorder) Load(root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStore)(nil).Load), root)
}

// Save mocks base method.
func (m *MockStore) Save(root string, arg1 lock.Lock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", root, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(root, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), root, arg1)
}
