// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/poconnor/graft/internal/pin (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -destination=mock/handler.go -package=mock github.com/poconnor/graft/internal/pin Handler
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/poconnor/graft/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockHandler) Detect(command string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", command)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockHandlerMockRecorder) Detect(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockHandler)(nil).Detect), command)
}

// Inject mocks base method.
func (m *MockHandler) Inject(pin model.Pin, args []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inject", pin, args)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Inject indicates an expected call of Inject.
func (mr *MockHandlerMockRecorder) Inject(pin, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockHandler)(nil).Inject), pin, args)
}

// Validate mocks base method.
func (m *MockHandler) Validate(pin model.Pin, installedVersion string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", pin, installedVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockHandlerMockRecorder) Validate(pin, installedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockHandler)(nil).Validate), pin, installedVersion)
}
