// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/poconnor/graft/internal/render (interfaces: Adapter)
//
// Generated by this command:
//
//	mockgen -destination=mock/adapter.go -package=mock github.com/poconnor/graft/internal/render Adapter
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/poconnor/graft/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockAdapter) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockAdapterMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAdapter)(nil).Remove), name)
}

// Render mocks base method.
func (m *MockAdapter) Render(mcp model.Definition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", mcp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockAdapterMockRecorder) Render(mcp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockAdapter)(nil).Render), mcp)
}

// TargetFile mocks base method.
func (m *MockAdapter) TargetFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TargetFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// TargetFile indicates an expected call of TargetFile.
func (mr *MockAdapterMockRecorder) TargetFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetFile", reflect.TypeOf((*MockAdapter)(nil).TargetFile))
}
